/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cw2.t1;

import javax.swing.JOptionPane;
import java.util.regex.*;
import javax.swing.ButtonGroup;

/**
 *
 * @author PMSU
 */
public class SignIn2 extends javax.swing.JFrame {

    public static String L;
    public static String M;
    public static String S;
    public static String package1;
    public static String duration;
    Double total;
    /**
     * Creates new form SignIn2
     */
    public SignIn2() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(rblarge);
        group.add(rbmedium);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblwms = new javax.swing.JLabel();
        lblwms1 = new javax.swing.JLabel();
        lblwms2 = new javax.swing.JLabel();
        lblback = new javax.swing.JLabel();
        lblpackage = new javax.swing.JLabel();
        lblcrates = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lblvalid = new javax.swing.JLabel();
        btnnext = new javax.swing.JButton();
        txtM = new javax.swing.JTextField();
        lblvalid1 = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();
        txtL = new javax.swing.JTextField();
        lblL = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblS = new javax.swing.JLabel();
        rblarge = new javax.swing.JRadioButton();
        rbmedium = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblsL = new javax.swing.JLabel();
        lblsM = new javax.swing.JLabel();
        lblsS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Warehouse Management System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 95, 79));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw2/t1/warehouse_64px.png"))); // NOI18N

        lblwms.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms.setForeground(new java.awt.Color(255, 255, 255));
        lblwms.setText("Warehouse");

        lblwms1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms1.setForeground(new java.awt.Color(255, 255, 255));
        lblwms1.setText("Management");

        lblwms2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms2.setForeground(new java.awt.Color(255, 255, 255));
        lblwms2.setText("System");

        lblback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw2/t1/back_48px.png"))); // NOI18N
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblbackMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(lblback)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel2)
                        .addComponent(lblwms)
                        .addComponent(lblwms1)
                        .addComponent(lblwms2))
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jLabel2)
                    .addGap(49, 49, 49)
                    .addComponent(lblwms, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addComponent(lblwms1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(95, 95, 95)
                    .addComponent(lblwms2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        lblpackage.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblpackage.setForeground(new java.awt.Color(0, 0, 0));
        lblpackage.setText("Package type :");

        lblcrates.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblcrates.setForeground(new java.awt.Color(0, 0, 0));
        lblcrates.setText("Num of crates you wanna store :");

        lbltime.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 0, 0));
        lbltime.setText("Duration (Months) :");

        lblvalid.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        lblvalid.setForeground(new java.awt.Color(0, 0, 0));
        lblvalid.setText("*All the reservations are valid for a month");

        btnnext.setBackground(new java.awt.Color(0, 95, 79));
        btnnext.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnnext.setForeground(new java.awt.Color(255, 255, 255));
        btnnext.setText("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        txtM.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMKeyReleased(evt);
            }
        });

        lblvalid1.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        lblvalid1.setForeground(new java.awt.Color(0, 0, 0));
        lblvalid1.setText("*1m2 = 1 Large , 1m2 = 2 Medium , 1m2 = 4 Small");

        txtS.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSKeyReleased(evt);
            }
        });

        txtL.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLKeyReleased(evt);
            }
        });

        lblL.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblL.setForeground(new java.awt.Color(0, 0, 0));
        lblL.setText("L :");

        lblM.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblM.setForeground(new java.awt.Color(0, 0, 0));
        lblM.setText("M :");

        lblS.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblS.setForeground(new java.awt.Color(0, 0, 0));
        lblS.setText("S :");

        rblarge.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        rblarge.setText("Large - 100m2");

        rbmedium.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        rbmedium.setText("Medium - 50m2");

        jComboBox1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Month", "2 Months", "3 Months" }));

        lblsL.setFont(new java.awt.Font("Consolas", 2, 28)); // NOI18N
        lblsL.setForeground(new java.awt.Color(204, 0, 0));

        lblsM.setFont(new java.awt.Font("Consolas", 2, 28)); // NOI18N
        lblsM.setForeground(new java.awt.Color(204, 0, 0));

        lblsS.setFont(new java.awt.Font("Consolas", 2, 28)); // NOI18N
        lblsS.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblvalid1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblcrates)
                            .addComponent(lblpackage)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbmedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rblarge, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblL)
                                .addGap(4, 4, 4)
                                .addComponent(txtL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(lblsL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(lblM)
                                .addGap(4, 4, 4)
                                .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(lblsM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblS)
                                .addGap(4, 4, 4)
                                .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(lblsS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lbltime))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblpackage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rblarge)
                .addGap(18, 18, 18)
                .addComponent(rbmedium)
                .addGap(15, 15, 15)
                .addComponent(lblcrates)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblsL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblL)
                                .addComponent(lblM)
                                .addComponent(lblS))
                            .addComponent(lblsS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addComponent(lbltime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblvalid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvalid1)
                .addGap(41, 41, 41)
                .addComponent(btnnext)
                .addGap(31, 31, 31))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1043, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        int i=1;
         L = txtL.getText();
         M = txtM.getText();
         S = txtS.getText();
         duration = jComboBox1.getSelectedItem().toString();
        
        if(!rblarge.isSelected() && !rbmedium.isSelected()) {
            JOptionPane.showMessageDialog(null,"Please select a package");
        }
        else{
        if(rblarge.isSelected()){
        package1 = "Large";
        }
        else{
        package1 = "Medium";
        }
        if(L.equals("") || M.equals("") || S.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the no of crates");
            i=0;
        }
        
        if(lblsL.getText()=="*" || lblsM.getText()=="*"|| lblsS.getText()=="*"){
        JOptionPane.showMessageDialog(null,"Please enter valid details");
            i=0;
        } 
        if(i==1){
        total = Double.parseDouble(txtL.getText()) + (Double.parseDouble(txtM.getText())/2) + (Double.parseDouble(txtS.getText())/4); 
        
        if(rblarge.isSelected()){
          if(total>100){
            JOptionPane.showMessageDialog(null,"Enter a valid num of crates suitable for your package");
            i=0;
        }
        }
        else{
          if(total>50){
            JOptionPane.showMessageDialog(null,"Enter a valid num of crates suitable for your package");
            i=0;
        }
        }
        }
              
        if(i==1){
            try {
                new MailVerification().setVisible(true);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }       
    }//GEN-LAST:event_btnnextActionPerformed
    }
    private void txtLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLKeyReleased
        // TODO add your handling code here:
        try {
        String PATTERN = "^[0-9]{0,3}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtL.getText());
        
        if(!match.matches()){
            lblsL.setText("*");
        }
        else{
            lblsL.setText(null);
        }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtLKeyReleased

    private void txtMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMKeyReleased
        // TODO add your handling code here:
        try {
        String PATTERN = "^[0-9]{0,3}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtM.getText());
        
        if(!match.matches()){
            lblsM.setText("*");
        }
        else{
            lblsM.setText(null);
        }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtMKeyReleased

    private void txtSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSKeyReleased
        // TODO add your handling code here:
        try {
        String PATTERN = "^[0-9]{0,3}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtS.getText());
        
        if(!match.matches()){
            lblsS.setText("*");
        }
        else{
            lblsS.setText(null);
        }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtSKeyReleased

    private void lblbackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseReleased
        // TODO add your handling code here:
        new SignIn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblbackMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnext;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblL;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblcrates;
    private javax.swing.JLabel lblpackage;
    private javax.swing.JLabel lblsL;
    private javax.swing.JLabel lblsM;
    private javax.swing.JLabel lblsS;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lblvalid;
    private javax.swing.JLabel lblvalid1;
    private javax.swing.JLabel lblwms;
    private javax.swing.JLabel lblwms1;
    private javax.swing.JLabel lblwms2;
    private javax.swing.JRadioButton rblarge;
    private javax.swing.JRadioButton rbmedium;
    private javax.swing.JTextField txtL;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtS;
    // End of variables declaration//GEN-END:variables
}
